[2023-08-29T15:11:12.936+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop permission to 509
[2023-08-29T15:11:12.938+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop'
[2023-08-29T15:11:12.972+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop permission to 509
[2023-08-29T15:11:12.973+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop'
[2023-08-29T15:11:13.020+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_bash_operator.run_after_loop scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-29T15:11:13.035+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_bash_operator.run_after_loop scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-29T15:11:13.036+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-29T15:11:13.059+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_after_loop> on 2023-08-28 00:00:00+00:00
[2023-08-29T15:11:13.067+0000] {standard_task_runner.py:57} INFO - Started process 3312 to run task
[2023-08-29T15:11:13.072+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'scheduled__2023-08-28T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', '/home/***/.local/lib/python3.8/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpanrwvt1r']
[2023-08-29T15:11:13.075+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask run_after_loop
[2023-08-29T15:11:13.131+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop permission to 509
[2023-08-29T15:11:13.133+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=run_after_loop'
[2023-08-29T15:11:13.136+0000] {task_command.py:415} INFO - Running <TaskInstance: example_bash_operator.run_after_loop scheduled__2023-08-28T00:00:00+00:00 [running]> on host a69c8752bcab
[2023-08-29T15:11:13.223+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_bash_operator' AIRFLOW_CTX_TASK_ID='run_after_loop' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-28T00:00:00+00:00'
[2023-08-29T15:11:13.226+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-29T15:11:13.227+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo 1']
[2023-08-29T15:11:13.241+0000] {subprocess.py:86} INFO - Output:
[2023-08-29T15:11:13.242+0000] {subprocess.py:93} INFO - 1
[2023-08-29T15:11:13.243+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-29T15:11:13.276+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20230828T000000, start_date=20230829T151113, end_date=20230829T151113
[2023-08-29T15:11:13.325+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-29T15:11:13.345+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
