[2023-09-14T14:30:55.146+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-14T14:30:55.148+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table'
[2023-09-14T14:30:55.200+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-14T14:30:55.203+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table'
[2023-09-14T14:30:55.268+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-12T00:00:00+00:00 [queued]>
[2023-09-14T14:30:55.287+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-12T00:00:00+00:00 [queued]>
[2023-09-14T14:30:55.288+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-14T14:30:55.318+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-12 00:00:00+00:00
[2023-09-14T14:30:55.330+0000] {standard_task_runner.py:57} INFO - Started process 197 to run task
[2023-09-14T14:30:55.334+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2023-09-12T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmp_d7aq9iy']
[2023-09-14T14:30:55.338+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask insert_into_table
[2023-09-14T14:30:55.413+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-14T14:30:55.415+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-12T00:00:00+00:00/task_id=insert_into_table'
[2023-09-14T14:30:55.420+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-12T00:00:00+00:00 [running]> on host 6c82fec646db
[2023-09-14T14:30:55.554+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-12T00:00:00+00:00'
[2023-09-14T14:30:55.556+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-12', 'dag_with_postgres_operator_v02')
        
[2023-09-14T14:30:55.572+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-14T14:30:55.587+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-14T14:30:55.594+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-12', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-14T14:30:55.596+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-14T14:30:55.613+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230912T000000, start_date=20230914T143055, end_date=20230914T143055
[2023-09-14T14:30:55.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-14T14:30:55.696+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
