[2023-09-02T08:51:54.197+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-02T08:51:54.198+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table'
[2023-09-02T08:51:54.236+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-02T08:51:54.237+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table'
[2023-09-02T08:51:54.275+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2023-09-02T08:51:54.288+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2023-09-02T08:51:54.289+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 9
[2023-09-02T08:51:54.307+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-01 00:00:00+00:00
[2023-09-02T08:51:54.313+0000] {standard_task_runner.py:57} INFO - Started process 773 to run task
[2023-09-02T08:51:54.315+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2023-09-01T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmpf_7v0qt0']
[2023-09-02T08:51:54.317+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask insert_into_table
[2023-09-02T08:51:54.368+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-02T08:51:54.369+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-01T00:00:00+00:00/task_id=insert_into_table'
[2023-09-02T08:51:54.372+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-01T00:00:00+00:00 [running]> on host 6c82fec646db
[2023-09-02T08:51:54.469+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-01T00:00:00+00:00'
[2023-09-02T08:51:54.471+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-01', 'dag_with_postgres_operator_v02')
        
[2023-09-02T08:51:54.484+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-02T08:51:54.495+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-02T08:51:54.499+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-01', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-02T08:51:54.502+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-02T08:51:54.516+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230901T000000, start_date=20230902T085154, end_date=20230902T085154
[2023-09-02T08:51:54.570+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-02T08:51:54.588+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
