[2023-08-29T15:11:10.081+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this permission to 509
[2023-08-29T15:11:10.082+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this'
[2023-08-29T15:11:10.123+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this permission to 509
[2023-08-29T15:11:10.125+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this'
[2023-08-29T15:11:10.169+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_bash_operator.also_run_this scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-29T15:11:10.181+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_bash_operator.also_run_this scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-29T15:11:10.182+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-29T15:11:10.198+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): also_run_this> on 2023-08-28 00:00:00+00:00
[2023-08-29T15:11:10.208+0000] {standard_task_runner.py:57} INFO - Started process 3283 to run task
[2023-08-29T15:11:10.216+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'scheduled__2023-08-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', '/home/***/.local/lib/python3.8/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpkoiileis']
[2023-08-29T15:11:10.221+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask also_run_this
[2023-08-29T15:11:10.298+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this permission to 509
[2023-08-29T15:11:10.300+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=also_run_this'
[2023-08-29T15:11:10.304+0000] {task_command.py:415} INFO - Running <TaskInstance: example_bash_operator.also_run_this scheduled__2023-08-28T00:00:00+00:00 [running]> on host a69c8752bcab
[2023-08-29T15:11:10.397+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_bash_operator' AIRFLOW_CTX_TASK_ID='also_run_this' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-28T00:00:00+00:00'
[2023-08-29T15:11:10.401+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-29T15:11:10.402+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "ti_key=example_bash_operator__also_run_this__20230828"']
[2023-08-29T15:11:10.417+0000] {subprocess.py:86} INFO - Output:
[2023-08-29T15:11:10.419+0000] {subprocess.py:93} INFO - ti_key=example_bash_operator__also_run_this__20230828
[2023-08-29T15:11:10.420+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-29T15:11:10.461+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20230828T000000, start_date=20230829T151110, end_date=20230829T151110
[2023-08-29T15:11:10.511+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-29T15:11:10.541+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
