[2023-09-02T08:39:57.714+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table permission to 509
[2023-09-02T08:39:57.715+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table'
[2023-09-02T08:39:57.748+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table permission to 509
[2023-09-02T08:39:57.750+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table'
[2023-09-02T08:39:57.795+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-09-02T08:39:00.897632+00:00 [queued]>
[2023-09-02T08:39:57.807+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-09-02T08:39:00.897632+00:00 [queued]>
[2023-09-02T08:39:57.808+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 7
[2023-09-02T08:39:57.826+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-09-02 08:39:00.897632+00:00
[2023-09-02T08:39:57.832+0000] {standard_task_runner.py:57} INFO - Started process 310 to run task
[2023-09-02T08:39:57.834+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2023-09-02T08:39:00.897632+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmp61fmztoo']
[2023-09-02T08:39:57.836+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask create_postgres_table
[2023-09-02T08:39:57.885+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table permission to 509
[2023-09-02T08:39:57.886+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:39:00.897632+00:00/task_id=create_postgres_table'
[2023-09-02T08:39:57.890+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-09-02T08:39:00.897632+00:00 [running]> on host 6c82fec646db
[2023-09-02T08:39:57.996+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-02T08:39:00.897632+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-02T08:39:00.897632+00:00'
[2023-09-02T08:39:57.998+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-09-02T08:39:58.010+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-02T08:39:58.020+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-02T08:39:58.025+0000] {sql.py:418} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2023-09-02T08:39:58.080+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20230902T083900, start_date=20230902T083957, end_date=20230902T083958
[2023-09-02T08:39:58.129+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-02T08:39:58.148+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
