[2023-08-29T15:11:10.066+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2 permission to 509
[2023-08-29T15:11:10.068+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2'
[2023-08-29T15:11:10.111+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2 permission to 509
[2023-08-29T15:11:10.112+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2'
[2023-08-29T15:11:10.164+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_bash_operator.runme_2 scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-29T15:11:10.176+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_bash_operator.runme_2 scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-29T15:11:10.177+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-29T15:11:10.195+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): runme_2> on 2023-08-28 00:00:00+00:00
[2023-08-29T15:11:10.206+0000] {standard_task_runner.py:57} INFO - Started process 3282 to run task
[2023-08-29T15:11:10.214+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'runme_2', 'scheduled__2023-08-28T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', '/home/***/.local/lib/python3.8/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpp9tjhw9h']
[2023-08-29T15:11:10.221+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask runme_2
[2023-08-29T15:11:10.292+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2 permission to 509
[2023-08-29T15:11:10.293+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_bash_operator/run_id=scheduled__2023-08-28T00:00:00+00:00/task_id=runme_2'
[2023-08-29T15:11:10.296+0000] {task_command.py:415} INFO - Running <TaskInstance: example_bash_operator.runme_2 scheduled__2023-08-28T00:00:00+00:00 [running]> on host a69c8752bcab
[2023-08-29T15:11:10.390+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_bash_operator' AIRFLOW_CTX_TASK_ID='runme_2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-28T00:00:00+00:00'
[2023-08-29T15:11:10.392+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-29T15:11:10.394+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "example_bash_operator__runme_2__20230828" && sleep 1']
[2023-08-29T15:11:10.409+0000] {subprocess.py:86} INFO - Output:
[2023-08-29T15:11:10.411+0000] {subprocess.py:93} INFO - example_bash_operator__runme_2__20230828
[2023-08-29T15:11:11.413+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-29T15:11:11.444+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_2, execution_date=20230828T000000, start_date=20230829T151110, end_date=20230829T151111
[2023-08-29T15:11:11.512+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-29T15:11:11.552+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
