[2023-09-05T02:58:07.596+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-05T02:58:07.598+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table'
[2023-09-05T02:58:07.640+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-05T02:58:07.643+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table'
[2023-09-05T02:58:07.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-09-05T02:58:07.716+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-09-05T02:58:07.717+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-05T02:58:07.740+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-04 00:00:00+00:00
[2023-09-05T02:58:07.748+0000] {standard_task_runner.py:57} INFO - Started process 184 to run task
[2023-09-05T02:58:07.754+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2023-09-04T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmp8h3bw7gz']
[2023-09-05T02:58:07.758+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask insert_into_table
[2023-09-05T02:58:07.821+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-05T02:58:07.823+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-04T00:00:00+00:00/task_id=insert_into_table'
[2023-09-05T02:58:07.826+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-04T00:00:00+00:00 [running]> on host 6c82fec646db
[2023-09-05T02:58:07.926+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-04T00:00:00+00:00'
[2023-09-05T02:58:07.927+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-04', 'dag_with_postgres_operator_v02')
        
[2023-09-05T02:58:07.939+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-05T02:58:07.949+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-05T02:58:07.954+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-04', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-05T02:58:07.961+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-05T02:58:07.974+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230904T000000, start_date=20230905T025807, end_date=20230905T025807
[2023-09-05T02:58:08.007+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-05T02:58:08.024+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
